fixing checks

diff --git a/.github/workflows/branch-name.yml b/.github/workflows/branch-name.yml
--- a/.github/workflows/branch-name.yml
+++ b/.github/workflows/branch-name.yml
@@ -14,5 +14,5 @@ jobs:
         env:
           BRANCH: ${{ github.head_ref }}
         run: |
-          echo "$BRANCH" | grep -Eq '^((feature|bugfix|hotfix|docs|poc)/LDS-[0-9]{1,4}|dependabot/.+)$' \
-            || { echo "::error::Invalid branch. Pattern: {type}/LDS-XXXX"; exit 1; }
+          echo "$BRANCH" | grep -Eq '^((feature|bugfix|hotfix|docs|poc|arch)/LDS-[1-9][0-9]{0,3}(-[a-z0-9]+)*|dependabot/.+)$' \
+            || { echo "::error::Invalid branch. Pattern: {type}/LDS-XXXX[-kebab-description]"; exit 1; }
